# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('styles.py',        '.'),
        ('database.py',      '.'),
        ('updater.py',       '.'),
        ('hammadde.py',      '.'),
        ('satinalma.py',     '.'),
        ('dashboard.py',     '.'),
        ('stok_liste.py',    '.'),
        ('etiket_panel.py',  '.'),
        ('analiz.py',        '.'),
        ('barcode_helper.py','.'),
        ('ayarlar.py',       '.'),
        ('cariler.py',       '.'),
        ('muhasebe.py',      '.'),
        ('sevkiyat.py',      '.'),
        ('siparis.py',       '.'),
        ('uretim.py',        '.'),
        ('kullanici.py',     '.'),
        ('log.py',           '.'),
        ('piyasa.py',        '.'),
        ('finans.py',        '.'),
    ],
    hiddenimports=[
        'updater',
        'requests',
        'urllib.request',
        'urllib.error',
        'reportlab',
        'reportlab.lib',
        'reportlab.pdfgen',
        'reportlab.platypus',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ArsacMetalERP',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
